FROM ubuntu
LABEL Maintainer="Billy <billy@domain.edu>"
LABEL Description="Ubuntu with updates, vim-nox and apache2 with entry-point."

# Skip prompts
ARG DEBIAN_FRONTEND=noninteractive

# Update packages
RUN apt update; apt full-upgrade -y

# Install packages
RUN apt install -y apache2 vim-nox

# Set entry-point
ENTRYPOINT apache2ctl -D FOREGROUND
